/// Flutter icons SportIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SportIcons
///      fonts:
///       - asset: fonts/SportIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SportIcons {
  SportIcons._();

  static const _kFontFam = 'SportIcons';
  static const String? _kFontPkg = null;

  static const IconData tennis = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basketball = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData squash = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volleyball = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cricket = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badmiton = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
